SmartThingsCommunity/st-device-sdk-c-ref

- patches/esp8266/1006-mbedtls-esp-add-support-eckey-alt-that-use-iot-secur.patch
> Develop rel 1.2.1

- build.sh
- patches/esp32/1001-mbedtls-esp-add-support-eckey-alt-that-use-iot-secur.patch.manual
- patches/esp32/1002-mbedtls-esp_config-added-CONFIG_STDK_IOT_CORE_MBEDTL.patch
- tools/esp32/setup_esp32.sh
STDK Ref ver 1.2.2 release to develop branch
> Develop rel 1.2.2

- apps/esp8266/light_example/main/iot_uart_cli.c
- apps/esp8266/switch_example/main/iot_uart_cli.c
Instead of the hardcoded value, set the baud rate from the config.
> use the configured baud rate for esp8266

- tools/esp32/build_esp32.py
Signed-off-by: Hyundo Lee <54927573+hdlee27@users.noreply.github.com>
> Fix false error message in esp32 build script

- doc/getting_started.md
Signed-off-by: Kwang-Hui Cho <54692798+Kwang-Hui@users.noreply.github.com>
> doc: getting_started: fix newline

- README.md
> Develop rel 1 4 4

- patches/emw3080/0007-add-CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP_USE_SOCKET_A.patch
- patches/emw3166/0007-add-CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP_USE_SOCKET_A.patch
Signed-off-by: Hyundo Lee <54927573+hdlee27@users.noreply.github.com>
> patch:emw3xxx:add CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP_USE_SOCKET_API

- apps/capability_sample/caps_button.c
- build.py
- doc/getting_started.md
- setup.py
> Develop rel 1 5 11

- apps/capability_sample/caps_energyMeter.c
- apps/capability_sample/caps_energyMeter.h
- apps/capability_sample/caps_fanOscillationMode.c
- apps/capability_sample/caps_fanOscillationMode.h
- apps/capability_sample/caps_imageCapture.c
- apps/capability_sample/caps_imageCapture.h
> Develop rel 1 7 1

- README.md
- [ x] I have read the [Contributing Guidelines](https://github.com/SmartThingsCommunity/st-device-sdk-c/blob/master/CONTRIBUTING.md).
- [ x] I have read the [Samsung Individual CLA](https://github.com/SmartThingsCommunity/st-device-sdk-c/blob/master/doc/SAMSUNGCLA.docx) and agree with it
- [x ] This pull-request is based on the latest [develop](https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/tree/develop) branch.
- [x ] I have ensured local tests pass about my code changes.
Your contribution will be licensed under the [Apache License …
> Revising README with new copyedits to match docs portal content

- apps/capability_sample/caps_operatingState.c
- apps/capability_sample/caps_operatingState.h
> Develop rel 1 7 4

- apps/capability_sample/caps_operatingState.c
- apps/capability_sample/caps_operatingState.h
> Master rel 1 7 4

- apps/esp32/code_lab_example/main/main.c
modify code_lab_example mispell
> esp32: modify code_lab_example mispell

- doc/getting_started.md
SmartThings Developer Website external link update
> doc: getting_started: update smartthings docs link

- apps/capability_sample/caps_tvocHealthConcern.c
- apps/capability_sample/caps_tvocHealthConcern.h
> feat : Add tvocHealthConcern cap helper sample example

- apps/esp32/light_example/main/main.c
> feat : Update Device Preference example

- apps/capability_sample/caps_carbonDioxideHealthConcern.c
- apps/capability_sample/caps_carbonDioxideHealthConcern.h
- apps/capability_sample/caps_dustHealthConcern.c
- apps/capability_sample/caps_dustHealthConcern.h
- apps/capability_sample/caps_fineDustHealthConcern.c
- apps/capability_sample/caps_fineDustHealthConcern.h
- apps/capability_sample/caps_moldHealthConcern.c
- apps/capability_sample/caps_moldHealthConcern.h
- apps/capability_sample/caps_panicAlarm.c
- apps/capability_sample/caps_panicAlarm.h
- apps/capability_sample/caps_radonHealthConcern.c
- apps/capability_sample/caps_radonHealthConcern.h
- apps/capability_sample/caps_veryFineDustHealthConcern.c
- apps/capability_sample/caps_veryFineDustHealthConcern.h
- carbonDioxideHealthConcern
- dustHealthConcern
- fineDustHealthConcern
- moldHealthConcern
- panicAlarm
- radonHealthConcern
- veryFineDustHealthConcern
> feat : Add capabilities samples

- apps/capability_sample/caps_tvocHealthConcern.c
> bugfix : Fix ENUM MAX code in caps_tvocHealthConcern.c

- apps/capability_sample/caps_remoteControlStatus.c
- apps/capability_sample/caps_remoteControlStatus.h
> feat : Add Remote Control Status Capability helper sample

- README.md
- doc/getting_started.md
- doc/ota_demo.md
> feat : Update documentation change

- doc/nvs_encryption_esp32.md
> doc: nvs encryption setup for esp32
